//https://api.themoviedb.org/3/movie/popular?api_key=67cc884deceda0099ac029e86eebea7d

//https://api.themoviedb.org/3/movie/top_rated?api_key=67cc884deceda0099ac029e86eebea7d

https://api.themoviedb.org/3/movie/upcoming?api_key=67cc884deceda0099ac029e86eebea7d